In [1]:
#HOMEWORK COCO2_PYTHON_BASICS
import numpy as np

In [2]:
# 1° Task
# 1. Crea una lista con los nombres de todos los planetas del sistema solar (en orden). Es un Strings!
planetas = ('Mercurio', 'Venus', 'Tierra','Marte','Jupiter','Saturno','Urano','Neptuno','Pluton')
planetas

('Mercurio',
 'Venus',
 'Tierra',
 'Marte',
 'Jupiter',
 'Saturno',
 'Urano',
 'Neptuno',
 'Pluton')

In [3]:
# 2. Haz que Python te diga cuántos planetas hay examinando tu lista
len(planetas)

9

In [4]:
# 3. Muestre los primeros cuatro planetas del sistema solar (los planetas rocosos).
#Usar los corchetes o no funciona!!
print(planetas[0:4])

('Mercurio', 'Venus', 'Tierra', 'Marte')


In [ ]:
T = 30.3 ^\circ\text{F} $$

# Conviertan este valor a grados Celsius, sabiendo que:
# $$ [^\circ\text{C}] = \frac{5}{9} ([^\circ\text{F}] - 32) $$

# Requerimientos:

# Asignar el dato recibido a una variable.
# Aplicar la transformación de unidades usando esta variable.
# Guardar el dato en Celsius en otra variable.
# Utilizar la función print para mostrar ambos resultados.

In [5]:
T_Farenheit = 30.3
T_Farenheit

30.3

In [6]:
T_Celsius = T_Farenheit*9/5-32
T_Celsius

22.54

In [ ]:
# 3° Task
#Dado el array: `([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])` investigue la documentación de la 
#librería `numpy` para "reshape" o reformular el array para que sea de 4x4.

In [7]:
np.reshape?

Signature: np.reshape(a, newshape, order='C')
Docstring:
Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
newshape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is
    inferred from the length of the array and remaining dimensions.
order : {'C', 'F', 'A'}, optional
    Read the elements of `a` using this index order, and place the
    elements into the reshaped array using this index order.  'C'
    means to read / write the elements using C-like index order,
    with the last axis index changing fastest, back to the first
    axis index changing slowest. 'F' means to read / write the
    elements using Fortran-like index order, with the first index
    changing fastest, and the last index changing slowest. Note that
    the 'C' and 'F' options ta

In [8]:
a = ([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [9]:
np.reshape(a, (4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# 4° Task
# NumPy nos permite también aplicar funciones matemáticas.

# Calcule el seno y el coseno de los ángulos: 0, 30, 45, 60 y 90 dados en grados:

In [10]:
# Cree un array con los ángulos mencionados en grados.
ang_grad = ([0, 30, 45, 60, 90])       # 0, n.pi/6, n.pi/4, n.pi/6/3, n.pi/2 es en radianes
ang_grad

[0, 30, 45, 60, 90]

In [12]:
# Convierta los ángulos a radianes.
ang_rad = np.deg2rad(ang_grad)
ang_rad

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [13]:
# Calcule el seno y el coseno de estos ángulos y guárdelos en dos arrays diferentes
sen_grad = np.sin(ang_grad)
sen_grad

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [14]:
sen_grad = np.cos(ang_grad)
sen_grad

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

In [ ]:
# Investigue la librería numpy para encontrar las funciones que permitan convertir los ángulos en grados a radianes
# y calcular el seno y coseno.

In [15]:
# Calcule el seno y el coseno de estos ángulos y guárdelos en dos arrays diferentes.
sen_rad = np.sin(ang_rad)
sen_rad

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [16]:
cos_rad = np.cos(ang_rad)
cos_rad

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [ ]:
# 5° Task

#Una aproximación común para calcular derivadas de funciones es una aproximación en diferencias finitas:

#$$\frac{d}{dx} y(x) = \frac{y(x + \Delta x) - y(x)}{\Delta x}$$

#o para datos discretos

#$$\frac{d}{dx} y(x_i) = \frac{y(x_i + \Delta x) - y(x_i)}{\Delta x} = \frac{y(x_{i+1}) - y(x_i)}{x_{i+1} - x_{i}}$$

#Esta operación se puede realizar utilizando las operaciones algebraicas vectorizadas, indices y silce. 
#¡Intenta calcularlo para la función cuadrática!

#Ahora, lea la documentación de Numpy para encontrar una función para poder calcular $\frac{d}{dx} y(x_i)$.